# Generated by Django 6.0.4 on 2026-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_room_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('freelance', 'Freelance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
